### ISSUE TITLE
Should reject return response vs err?

### ISSUE THREAD

**Issue by eddywashere** [blakeembrey/popsicle-status#1]
Any reason why a generic error is returned vs just the response?

use case: I'd like to use the original response to throw a custom error.

**Comment by blakeembrey** [comment]
What do you mean by "just the response"? This module is meant to reject invalid HTTP statuses.

**Comment by eddywashere** [comment]
Here's an example of what I'm using currently:

```
req.after(function(res) {
      if (res.status >= lower && res.status <= upper) {
        return Promise.resolve(res);
      }

      return Promise.reject(res);
});
```

From here I can catch errors and access things like the response body that could include things like valuable error messages re: `missing parameter name`.

**Comment by blakeembrey** [comment]
You should be able to do that already. By rejecting using the built in `res.error` function, it's added a `popsicle` property for you to access. Try something like `error.popsicle.response.<blah>`?

**Comment by blakeembrey** [comment]
Here's the documentation: https://github.com/blakeembrey/popsicle#error-handling. This module should probably update to the proper 1.0 API though, so I can make a minor release for that (E.g. providing the `type`).

**Comment by blakeembrey** [comment]
@eddywashere I made some tweaks and improved the README. Let me know if the information I provided solves the issue for you, or if I've interpreted your need incorrectly.

**Comment by eddywashere** [comment]
:+1: thanks for the quick responses
